name: CI/CD ticket_bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH key
        run: |
          ls -l ~/.ssh
          cat ~/.ssh/id_rsa
          cat ~/.ssh/known_hosts

      - name: Create directory on server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} 'mkdir -p ~/home/ticket_bot'

      - name: Copy files via SSH
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:~/home/ticket_bot/

      - name: SSH into server and build Docker image
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            cd ~/home/ticket_bot
            docker build -t ticket_bot:latest .
            docker stop ticket_bot || true
            docker rm ticket_bot || true
            docker run -d --name ticket_bot --restart=unless-stopped \
              -e API_TOKEN=${{ secrets.API_TOKEN }} \
              order_apts_consumer:latest
          EOF